name: Cloud_to_butt
main: net.simpvp.Cloud_to_butt.Cloud_to_butt
version: 1
author: simpvp.net
website: https://github.com/C4K3/cloud-to-butt-bukkit
api-version: 1.13
description: Replaces in chat "the cloud" -> "my butt", "cloud" -> "butt"
